apiVersion: provisioning.cattle.io/v1
kind: Cluster
metadata:
  name: {{ .Values.cluster.name }}
  namespace: fleet-default
spec:
  cloudCredentialSecretName: {{ .Values.cloudCredentialSecretName }}
  kubernetesVersion: {{ .Values.kubernetesVersion }}
  rkeConfig:
    machinePools:
    {{- range .Values.nodepool }}
    - controlPlaneRole: {{ .controlplane | default false }}
      etcdRole: {{ .etcd | default false }}
      workerRole: {{ .worker | default false }}
      quantity: {{ .quantity | default 1 }}
      name: {{ .name }}-nodes
      machineConfigRef:
        kind: VmwarevsphereConfig
        name: {{ .name }}-nodes
      paused: {{ .paused | default false }}
      displayName: {{ .name }}-nodes
    {{- end }}
    machineGlobalConfig:
      cni: cilium
