{{- range .Values.nodepool }}
apiVersion: rke-machine-config.cattle.io/v1
kind: VmwarevsphereConfig
metadata:
  name: {{ .name }}-nodes
  namespace: fleet-default
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "-1"
cloneFrom: {{ .cloneFrom | quote }}
cpuCount: {{ .cpuCount | quote }}
datacenter: {{ .datacenter | quote }}
datastore: {{ .datastore | quote }}
diskSize: {{ .diskSize | quote }}
folder: {{ .folder | quote }}
memorySize: {{ .memorySize | quote }}
network:
  {{- range .network }}
  - {{ . | quote }}
  {{- end }}
pool: {{ .pool | quote }}
sshPort: {{ .sshPort | quote }}
sshUserGroup: {{ .sshUserGroup | quote }}
vcenterPort: {{ .vcenterPort | quote }}
{{- end }}

