{{- range .Values.nodepool }}
apiVersion: rke-machine-config.cattle.io/v1
kind: VmwarevsphereConfig
metadata:
  name: {{ .name }}-nodes
  namespace: fleet-default
cloneFrom: {{ .cloneFrom }}
#cloudConfig: {{ .cloudConfig }}
#cloudinit: {{ .cloudinit }}
#contentLibrary: {{ .contentLibrary }}
cpuCount: {{ .cpuCount }}
#creationType: {{ .creationType }}
#customAttribute: {{ .customAttribute }}
datacenter: {{ .datacenter }}
datastore: {{ .datastore }}
datastoreCluster: {{ .datastoreCluster }}
diskSize: {{ .diskSize }}
folder: {{ .folder }}
#hostsystem: {{ .hostsystem }}
memorySize: {{ .memorySize }}
network: 
  {{- range .network }}
  - {{ . }}
  {{- end }}
pool: {{ .pool }}
sshPort: {{ .sshPort }}
sshUser: {{ .sshUser }}
sshUserGroup: {{ .sshUserGroup }}
#tag: {{ .tag }}
#vappIpallocationpolicy: {{ .vappIpallocationpolicy }}
#vappIpprotocol: {{ .vappIpprotocol }}
#vappProperty: {{ .vappProperty }}
#vappTransport: {{ .vappTransport }}
vcenter: {{ .vcenter }}
vcenterPort: {{ .vcenterPort }}
{{- end }}
