cloudprovider: vsphere
cloudCredentialSecretName: cc-z5wvg
kubernetesVersion: v1.27.16+rke2r2
monitoring:
  enabled: false
cluster:
  name: mycluster
nodepool:
- etcd: true
  controlplane: true
  worker: true
  name: vsphere-nodepool-1-adarsh
  cloneFrom: "/rancherdc/vm/templates-folder/ubuntu-22.04-cloudimg"
  cpuCount: "4"           # Wrapped in quotes
  creationType: "vm"
  datacenter: "rancherdc"
  datastore: "rancherdc/datastore/rancherDatastore01"
  datastoreCluster: ""
  diskSize: "20480"       # Wrapped in quotes
  folder: "/rancherdc/vm/adarshr-vm-folder"
  memorySize: "4096"      # Wrapped in quotes
  network: 
    - "/rancherdc/network/VM Network"
  pool: "/rancherdc/host/rancheresxi01.sup.scz.suse.com/Resources"
  sshPort: "22"           # Wrapped in quotes
  sshUserGroup: "staff"
  vcenterPort: "443"      # Wrapped in quotes
